services:
  - type: web
    name: zenova-license-server
    runtime: docker
    rootDir: license-server
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: SUPER_ADMIN_EMAIL
        value: super@zenova.app
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./data/zenova_cloud.db
      - key: CORS_ORIGINS
        value: '["*"]'
    autoDeploy: true