"""
ZENOVA License Key Generator

Generates RSA-2048 key pairs and signed .lic files for distribution.

Usage:
    python scripts/gen-license-keys.py --generate-keys
    python scripts/gen-license-keys.py --sign-lic <school_id> <school_name> <valid_until>

Examples:
    # Step 1: Generate a new RSA key pair
    python scripts/gen-license-keys.py --generate-keys

    # Step 2: Sign a MAIN license for a school
    python scripts/gen-license-keys.py --sign-lic \\
        --school-id "550e8400-e29b-41d4-a716-446655440000" \\
        --school-name "Addis Ababa International School" \\
        --license-type MAIN \\
        --valid-until "2027-12-31" \\
        --max-students 5000 \\
        --max-branches 3

    # Step 3: Sign a BRANCH license
    python scripts/gen-license-keys.py --sign-lic \\
        --school-id "550e8400-e29b-41d4-a716-446655440001" \\
        --school-name "AAIS - Bole Campus" \\
        --license-type BRANCH \\
        --valid-until "2027-12-31"

    # Step 4: Generate activation key (V2 format)
    python scripts/gen-license-keys.py --generate-key --type MAIN

Security Notes:
    - Keep private.pem OFFLINE (air-gapped machine or HSM)
    - Distribute public.pem with the application
    - .lic files are per-school, per-installation
    - Never share private.pem with anyone
"""

import argparse
import json
import os
import sys
import base64
import uuid
import hashlib, zlib
import secrets
from datetime import datetime, date
from pathlib import Path

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import rsa, padding
    from cryptography.hazmat.backends import default_backend
    HAS_CRYPTOGRAPHY = True
except ImportError:
    HAS_CRYPTOGRAPHY = False

PROJECT_DIR = Path(__file__).parent.parent
KEYS_DIR = PROJECT_DIR / "keys"
PUBLIC_KEY_OUTPUT = PROJECT_DIR / "app" / "licensing" / "public_key.py"


#  RSA Key Generation 

def generate_rsa_keypair():
    """Generate RSA-2048 key pair for license signing."""
    if not HAS_CRYPTOGRAPHY:
        print("ERROR: cryptography package required. Install: pip install cryptography")
        sys.exit(1)

    print("Generating RSA-2048 key pair...")
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend(),
    )

    KEYS_DIR.mkdir(parents=True, exist_ok=True)

    # Private key (PEM, unencrypted  we encrypt at rest separately)
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    (KEYS_DIR / "license_private.pem").write_bytes(private_pem)
    print(f"   Private key: keys/license_private.pem")
    print(f"   Key is unencrypted - store securely, use HSM in production")

    # Public key
    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    (KEYS_DIR / "license_public.pem").write_bytes(public_pem)
    print(f"   Public key: keys/license_public.pem")

    # Generate public_key.py for embedding in app
    _generate_public_key_py(public_pem)

    print(f"\n Key pair generated successfully!")
    print(f"   Keep keys/license_private.pem in a secure location (HSM recommended)")
    print(f"   Distribute keys/license_public.pem with the application")
    return private_key, public_pem


def _generate_public_key_py(public_pem: bytes):
    """Generate public_key.py with embedded PEM for the licensing module."""
    pem_str = public_pem.decode().strip()
    content = f'''"""
ZENOVA License Validation Public Key
Auto-generated by gen-license-keys.py  DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}
"""

# RSA-2048 Public Key for .lic file signature verification
# This is the PUBLIC key  safe to distribute with the application
LICENSE_PUBLIC_KEY_PEM = """{pem_str}"""
'''
    PUBLIC_KEY_OUTPUT.write_text(content)
    print(f"   Embedded public key: {PUBLIC_KEY_OUTPUT}")


#  V2 Activation Key Generation 

def generate_v2_key(license_type: str = "MAIN") -> str:
    """Generate a V2 format activation key."""
    type_map = {"MAIN": "M", "BRANCH": "B", "TRIAL": "T", "SUPER_ADMIN": "O"}
    prefix = type_map.get(license_type.upper(), "O")

    # 32 bytes (256 bits) of cryptographically secure random data
    random_bytes = secrets.token_bytes(32)

    # Base58 encode (no 0/O/I/l)
    base58_chars = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
    encoded = ""
    num = int.from_bytes(random_bytes, byteorder="big")
    while num > 0:
        num, rem = divmod(num, 58)
        encoded = base58_chars[rem] + encoded

    # Pad to expected length
    encoded = encoded.zfill(44)

    # CRC-32 checksum
    crc_data = (prefix + encoded).encode()
    crc = zlib.crc32(crc_data) & 0xFFFFFFFF

    # Encode CRC as base58
    crc_encoded = ""
    num = crc
    while num > 0:
        num, rem = divmod(num, 58)
        crc_encoded = base58_chars[rem] + crc_encoded
    crc_encoded = crc_encoded.zfill(6)

    return f"ZNV-{prefix}-{encoded}-{crc_encoded}"


def generate_legacy_key(license_type: str = "MAIN") -> str:
    """Generate a legacy format activation key (64-bit, 4 segments)."""
    segments = []
    for _ in range(4):
        segment = secrets.token_hex(2).upper()
        segments.append(segment)
    type_prefix = {"MAIN": "ZNV", "BRANCH": "ZNV", "TRIAL": "ZNV"}
    return f"{type_prefix.get(license_type, 'ZNV')}-{'-'.join(segments)}"


#  .lic File Signing 

def sign_license_file(
    school_id: str,
    school_name: str,
    license_type: str = "MAIN",
    valid_until: str = None,
    max_students: int = 1000,
    max_branches: int = 1,
    machine_fingerprint: str = "*",  # "*" means first-activation bind
    features: list = None,
):
    """Create and sign a .lic license file."""
    if not HAS_CRYPTOGRAPHY:
        print("ERROR: cryptography package required.")
        sys.exit(1)

    # Load private key
    private_key_path = KEYS_DIR / "license_private.pem"
    if not private_key_path.exists():
        print(f"ERROR: Private key not found at {private_key_path}")
        print("Run with --generate-keys first")
        sys.exit(1)

    private_key = serialization.load_pem_private_key(
        private_key_path.read_bytes(),
        password=None,
        backend=default_backend(),
    )

    if features is None:
        features = ["nfc", "qr", "import", "id_card"]

    # Build payload
    payload = {
        "school_id": school_id,
        "school_name": school_name,
        "license_type": license_type.upper(),
        "machine_fingerprint": machine_fingerprint,
        "valid_from": date.today().isoformat(),
        "valid_until": valid_until or "2099-12-31",
        "max_students": max_students,
        "max_branches": max_branches,
        "features": features,
        "issued_at": datetime.now(datetime.timezone.utc).isoformat(),
        "issuer": "ZENOVA License Server",
    }

    # Canonical payload JSON (this exact string is what gets signed)
    payload_json = json.dumps(payload, indent=2, ensure_ascii=False)

    # Sign canonical payload JSON with RSA-PSS + SHA-256
    signature = private_key.sign(
        payload_json.encode(),
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=32,
        ),
        hashes.SHA256(),
    )

    signature_b64 = base64.b64encode(signature).decode()

    # Store base64 of the canonical payload so the C verifier can extract
    # the EXACT bytes that were signed (no JSON escaping/nesting ambiguity)
    payload_b64 = base64.b64encode(payload_json.encode()).decode()

    # Build .lic file
    lic_data = {
        "payload": payload,
        "payload_b64": payload_b64,
        "signature": signature_b64,
        "format_version": 3,
    }

    lic_dir = PROJECT_DIR / "dist" / "licenses"
    lic_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{school_name.replace(' ', '_')}_{license_type}.lic"
    lic_path = lic_dir / filename
    lic_path.write_text(json.dumps(lic_data, indent=2, ensure_ascii=False))

    print(f" Signed license file: {lic_path}")
    print(f"   School: {school_name}")
    print(f"   Type: {license_type}")
    print(f"   Valid until: {valid_until or '2099-12-31'}")
    print(f"   Features: {', '.join(features)}")
    print(f"   Payload hash: {hashlib.sha256(payload_json.encode()).hexdigest()[:16]}...")
    return lic_path


#  Key Verification 

def verify_license_file(lic_path: Path):
    """Verify a .lic file's signature using the public key."""
    if not HAS_CRYPTOGRAPHY:
        print("ERROR: cryptography package required.")
        sys.exit(1)

    public_key_path = KEYS_DIR / "license_public.pem"
    if not public_key_path.exists():
        print(f"ERROR: Public key not found at {public_key_path}")
        sys.exit(1)

    public_key = serialization.load_pem_public_key(
        public_key_path.read_bytes(),
        backend=default_backend(),
    )

    lic_data = json.loads(lic_path.read_text())
    # Use payload_b64 if available (v3+), else reconstruct from payload dict
    if "payload_b64" in lic_data:
        payload_json = base64.b64decode(lic_data["payload_b64"]).decode()
    else:
        payload_json = json.dumps(lic_data["payload"], indent=2, ensure_ascii=False)
    signature = base64.b64decode(lic_data["signature"])

    try:
        public_key.verify(
            signature,
            payload_json.encode(),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=32,
            ),
            hashes.SHA256(),
        )
        print(f" Signature VALID  {lic_path.name}")
        print(f"   School: {lic_data['payload']['school_name']}")
        print(f"   Type: {lic_data['payload']['license_type']}")
        print(f"   Valid: {lic_data['payload']['valid_from']}  {lic_data['payload']['valid_until']}")
        return True
    except Exception as e:
        print(f" Signature INVALID  {lic_path.name}: {e}")
        return False


#  CLI 

def main():
    parser = argparse.ArgumentParser(description="ZENOVA License Key Generator")
    parser.add_argument("--generate-keys", action="store_true", help="Generate RSA-2048 key pair")
    parser.add_argument("--generate-key", action="store_true", help="Generate activation key")
    parser.add_argument("--type", choices=["MAIN", "BRANCH", "TRIAL", "SUPER_ADMIN"], default="MAIN")
    parser.add_argument("--format", choices=["v2", "legacy"], default="v2")

    parser.add_argument("--sign-lic", action="store_true", help="Sign a .lic file")
    parser.add_argument("--school-id", default=str(uuid.uuid4()))
    parser.add_argument("--school-name", default="Demo School")
    parser.add_argument("--license-type", choices=["MAIN", "BRANCH", "TRIAL", "LIFETIME"], default="MAIN")
    parser.add_argument("--valid-until", default=None)
    parser.add_argument("--max-students", type=int, default=1000)
    parser.add_argument("--max-branches", type=int, default=1)
    parser.add_argument("--features", nargs="+", default=["nfc", "qr", "import", "id_card"])

    parser.add_argument("--verify-lic", type=str, help="Verify a .lic file")

    args = parser.parse_args()

    if args.generate_keys:
        generate_rsa_keypair()

    elif args.generate_key:
        if args.format == "v2":
            key = generate_v2_key(args.type)
        else:
            key = generate_legacy_key(args.type)
        print(f"License Key ({args.type}, {args.format}): {key}")

    elif args.sign_lic:
        sign_license_file(
            school_id=args.school_id,
            school_name=args.school_name,
            license_type=args.license_type,
            valid_until=args.valid_until,
            max_students=args.max_students,
            max_branches=args.max_branches,
            features=args.features,
        )

    elif args.verify_lic:
        verify_license_file(Path(args.verify_lic))

    else:
        parser.print_help()
        print("\n--- Quick Start ---")
        print("1. Generate keys:  python scripts/gen-license-keys.py --generate-keys")
        print("2. Sign license:   python scripts/gen-license-keys.py --sign-lic \\")
        print("                     --school-name \"My School\" --valid-until 2027-12-31")
        print("3. Verify:         python scripts/gen-license-keys.py --verify-lic dist/licenses/My_School_MAIN.lic")


if __name__ == "__main__":
    main()




