"""
ZENOVA License Validation Public Key
Auto-generated by gen-license-keys.py  DO NOT EDIT MANUALLY
Generated: 2026-07-05T06:03:22.982743
"""

# RSA-2048 Public Key for .lic file signature verification
# This is the PUBLIC key  safe to distribute with the application
LICENSE_PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuZ+xKnBKH7/m3q1BZ3Rg
IrAUabbD48zBIDVHrzIwuUxZ4cQypzFTcow0uwpuaTSpn5NyJpneLA9gyCgCGcQa
+cSd+kuTTCkrRdjNMnNZYbyvBr1DYyX+LaLCpbO/6vDeaK6LUXV4fwrbhnld74r8
WQQXFId6UOzbN5zt6fj3J7nBeajGF3WwbjvxS6Z7AJ4KE4rYwbULamNO+Z69YdT1
mISH9k9QrN7iKTmOgZUzaxtebsVw4zgrhTHnE/M2qMYdQ5Rk6B5jxsQ97s04pdw2
BYEPBKFoJMzERlcsrze4PnIp60QgrpWHc7E8hBLMbDj2nkoOKC3sbCURpSjxaFhd
kQIDAQAB
-----END PUBLIC KEY-----"""


def get_license_public_key() -> str:
    """Return the RSA public key PEM for license signature verification."""
    return LICENSE_PUBLIC_KEY_PEM
