"""add_notification_prefs_and_telegram_bot

Revision ID: 6c759f002a02
Revises: 56e806ae8fa1
Create Date: 2026-06-25 21:14:21.487694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c759f002a02'
down_revision = '56e806ae8fa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email_on', sa.Boolean(), nullable=True),
    sa.Column('telegram_on', sa.Boolean(), nullable=True),
    sa.Column('sms_on', sa.Boolean(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('school_telegram_bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('bot_token', sa.Text(), nullable=False),
    sa.Column('bot_username', sa.String(length=100), nullable=True),
    sa.Column('bot_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'idempotency_key')
    op.drop_table('school_telegram_bots')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
