"""add_sync_queue

Revision ID: 73ccf4e21e6d
Revises: b8c9d0e1f2a3b4c5
Create Date: 2026-06-29 18:22:46.045381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73ccf4e21e6d'
down_revision = 'b8c9d0e1f2a3b4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='syncoperation'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='syncstatus'), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.String(length=10), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_queue_branch_id'), 'sync_queue', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_record_id'), 'sync_queue', ['record_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_school_id'), 'sync_queue', ['school_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_status'), 'sync_queue', ['status'], unique=False)
    op.create_index(op.f('ix_sync_queue_table_name'), 'sync_queue', ['table_name'], unique=False)
    op.alter_column('employee_contracts', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('exam_results', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('exam_types', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('exams', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('performance_reviews', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('promotion_records', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('report_cards', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.alter_column('scholarships', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sections', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('server_identities', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_server_identities_fingerprint'), table_name='server_identities')
    op.drop_constraint(op.f('server_identities_server_id_key'), 'server_identities', type_='unique')
    op.drop_index(op.f('ix_server_identities_server_id'), table_name='server_identities')
    op.create_index(op.f('ix_server_identities_server_id'), 'server_identities', ['server_id'], unique=True)
    op.alter_column('staff_profiles', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('subjects', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('teacher_grade_assignments', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('teacher_profiles', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('teacher_section_assignments', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('timetable_entries', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('wallet_transactions', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('wallets', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('wallet_transactions', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('timetable_entries', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('teacher_section_assignments', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('teacher_profiles', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('teacher_grade_assignments', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('subjects', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('staff_profiles', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_server_identities_server_id'), table_name='server_identities')
    op.create_index(op.f('ix_server_identities_server_id'), 'server_identities', ['server_id'], unique=False)
    op.create_unique_constraint(op.f('server_identities_server_id_key'), 'server_identities', ['server_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_server_identities_fingerprint'), 'server_identities', ['fingerprint_sha256'], unique=False)
    op.alter_column('server_identities', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sections', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('scholarships', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('report_cards', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('promotion_records', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('performance_reviews', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('exams', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('exam_types', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('exam_results', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('employee_contracts', 'school_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_sync_queue_table_name'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_status'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_school_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_record_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_branch_id'), table_name='sync_queue')
    op.drop_table('sync_queue')
    # ### end Alembic commands ###
