#!/usr/bin/env bash
# ZENOVA School ERP — Customer Installer
# Usage: bash install.sh
set -euo pipefail

echo "========================================"
echo "  ZENOVA School ERP — Installation"
echo "========================================"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "ERROR: Docker is required. Install at https://docs.docker.com/engine/install/"; exit 1; }
command -v docker compose >/dev/null 2>&1 || { echo "ERROR: Docker Compose is required."; exit 1; }

# Load images
echo "==> Loading Docker images..."
for img in zenova-backend-*.tar.gz; do
    [ -f "$img" ] && gunzip -c "$img" | docker load && echo "  Loaded $img"
done
for img in zenova-frontend-*.tar.gz; do
    [ -f "$img" ] && gunzip -c "$img" | docker load && echo "  Loaded $img"
done

# Create .env if missing
if [ ! -f ".env" ]; then
    echo "==> Creating .env file..."
    cat > .env << 'ENVEOF'
# ZENOVA Configuration
# Generated by installer — CHANGE THESE VALUES!
SECRET_KEY=
DB_PASSWORD=
ZENOVA_LICENSE_KEY=
ZENOVA_LICENSE_SERVER=https://superadmin.free.nf
SCHOOL_ID=
ENVIRONMENT=production
BACKEND_PORT=8000
FRONTEND_PORT=3000
DB_PORT=5432
REDIS_PORT=6379
ENVEOF
    echo "  Created .env — please edit with your settings"
    echo "  Run: nano .env"
    echo "  Then: docker compose up -d"
else
    echo "==> .env already exists, using it"
fi

echo ""
echo "==> To start ZENOVA:"
echo "    1. Edit .env with your license key and passwords"
echo "    2. docker compose up -d"
echo "    3. Access at http://YOUR_SERVER_IP:3000"
echo ""
echo "==> First-time setup:"
echo "    Default admin will be created on first startup"
echo "    Check logs: docker compose logs -f backend"
